diff_tf:
  ros__parameters:
    rate: 10
    ticks_meter: 320
    base_width: 0.245
    base_frame_id: base_footprint
    odom_frame_id: odom
    encoder_min: -32768
    encoder_max: 32768
    radius: 0.033
    left_wheel_frames:
      - wheel_front_left_link
      - wheel_back_left_link
    right_wheel_frames: 
      - wheel_front_right_link
      - wheel_back_right_link
    # wheel_low_wrap 
    # wheel_high_wrap

twist_to_motors:
  ros__parameters:
    base_width: 0.1
    rate: 50
    timeout_ticks: 2

