odometry_publisher:
  ros__parameters:
    publish_rate: 10
    wheel_diameter_left_front: 0.1651
    wheel_diameter_left_rear: 0.1651
    wheel_diameter_right_front: 0.1651
    wheel_diameter_right_rear: 0.1651
    wheel_separation: 0.3175
    slip_multiplier: 2.0
    invert_left_front: false
    invert_left_rear: false
    invert_right_front: true
    invert_right_rear: true
    


motor_control:
  ros__parameters:
    wheel_diameter_left_front: 0.1651
    wheel_diameter_left_rear: 0.1651
    wheel_diameter_right_front: 0.1651
    wheel_diameter_right_rear: 0.1651
    wheel_separation: 0.3175
    slip_multiplier: 2.0
    publish_rate: 10
