/camera_depth:
  ros__parameters:
    camera:
      i_nn_type: none
    stereo:
      i_align_depth: true
      i_board_socket_id: 2
      i_subpixel: true
      i_publish_right_rect: true
    left:
      r_focus: 1
      r_set_man_focus: true
      i_low_bandwidth: true
      i_low_bandwidth_quality: 50
    rgb:
      r_focus: 1
      r_set_man_focus: true
      i_low_bandwidth: true
      i_low_bandwidth_quality: 50
    right:
      r_focus: 1
      r_set_man_focus: true
      i_low_bandwidth: true
      i_low_bandwidth_quality: 50