/camera_depth:
  ros__parameters:
    # camera_i_nn_type: spatial
    camera:
      i_nn_type: none
      # i_usb_speed: SUPER_PLUS
      i_usb_speed: HIGH
        # {"LOW", dai::UsbSpeed::LOW},
        # {"FULL", dai::UsbSpeed::FULL},
        # {"HIGH", dai::UsbSpeed::HIGH},
        # {"SUPER", dai::UsbSpeed::SUPER},
        # {"SUPER_PLUS", dai::UsbSpeed::SUPER_PLUS},
    stereo:
      i_subpixel: true

    left:
      r_focus: 1
      r_set_man_focus: true
    rgb:
      r_focus: 1
      r_set_man_focus: true
      # i_low_bandwidth: true
      # i_low_bandwidth_quality: 50
    right:
      r_focus: 1
      r_set_man_focus: true