<?xml version="1.0" ?>
<robot name="deepdrive_deepdrive"
  xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:property name="wheel_base" value="0.175" />
  <xacro:property name="wheel_radius" value="0.035" />

  <xacro:include filename="$(find deepdrive_description)/urdf/common_properties.xacro"/>
  <xacro:include filename="$(find deepdrive_description)/urdf/wheels.xacro"/>


  <link name="base_footprint"/>

  <joint name="base_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link" />
    <origin xyz="0 0 0.010" rpy="0 0 0"/>
  </joint>

  <link name="base_link">
    <visual>
      <origin xyz="-0.064 0 0.0" rpy="0 0 1.57"/>
      <geometry>
        <mesh filename="package://deepdrive_description/meshes/bases/deepdrive_chassis.stl" scale="1 1 1"/>
      </geometry>
      <material name="grey"/>
    </visual>

    <collision>
      <origin xyz="-0.064 0 0.047" rpy="0 0 0"/>
      <geometry>
        <box size="0.310 0.140 0.120"/>
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="2.3729096e+00"/>
      <inertia ixx="8.7002718e-03" ixy="-4.7576583e-05" ixz="1.1160499e-04" iyy="8.6195418e-03" iyz="-3.5422299e-06" izz="1.4612727e-02" />
    </inertial>
  </link>

  <gazebo reference="base_link">
    <material>Gazebo/Grey</material>
  </gazebo>


  <xacro:wheel name="front_right" lr="1" fb="1" wheel_base="${wheel_base}" wheel_radius="${wheel_radius}" />
  <xacro:wheel name="back_right" lr="1" fb="-1" wheel_base="${wheel_base}" wheel_radius="${wheel_radius}" />
  <xacro:wheel name="front_left" lr="-1" fb="-1" wheel_base="${wheel_base}" wheel_radius="${wheel_radius}" />
  <xacro:wheel name="back_left" lr="-1" fb="1" wheel_base="${wheel_base}" wheel_radius="${wheel_radius}" />



  <!-- <joint name="imu_joint" type="fixed">
    <parent link="base_link"/>
    <child link="imu_link"/>
    <origin xyz="0.0 0 0.068" rpy="0 0 0"/>
  </joint>

  <link name="imu_link"/>

   <joint name="oak_joint" type="fixed">
    <parent link="base_link"/>
    <child link="oak"/>
    <origin xyz="0.0 0 0.068" rpy="0 0 1.57"/>
  </joint>

  <link name="oak"/> -->


  <!-- LIDAR -->
  <xacro:include filename="$(find deepdrive_description)/urdf/lidar.xacro" />

  <xacro:include filename="$(find deepdrive_description)/urdf/camera.xacro" />



  <gazebo>
    <plugin name='diff_drive' filename='libgazebo_ros_diff_drive.so'>


      <!-- Wheel Information -->
      <num_wheel_pairs>2</num_wheel_pairs>
      <left_joint>wheel_front_left_joint</left_joint>
      <right_joint>wheel_front_right_joint</right_joint>
      <left_joint>wheel_back_left_joint</left_joint>
      <right_joint>wheel_back_right_joint</right_joint>
      <wheel_separation>${wheel_base}</wheel_separation>
      <wheel_diameter>${wheel_radius*2}</wheel_diameter>

      <!-- Limits -->
      <max_wheel_torque>200</max_wheel_torque>
      <max_wheel_acceleration>10.0</max_wheel_acceleration>


      <!-- Output -->
      <odometry_frame>odom</odometry_frame>
      <robot_base_frame>base_footprint</robot_base_frame>

      <publish_odom>true</publish_odom>
      <publish_odom_tf>true</publish_odom_tf>
      <publish_wheel_tf>true</publish_wheel_tf>

         <!-- <ros>
        <namespace>/demo</namespace>
        <remapping>cmd_vel:=cmd_demo</remapping>
        <remapping>odom:=odom_demo</remapping>
      </ros> -->

      <!-- <updateRate>100.0</updateRate>
      <robotNamespace>/</robotNamespace>
      <leftFrontJoint>wheel_front_left_joint</leftFrontJoint>
      <rightFrontJoint>wheel_front_right_joint</rightFrontJoint>
      <leftRearJoint>wheel_back_left_joint</leftRearJoint>
      <rightRearJoint>wheel_back_right_joint</rightRearJoint>
      <wheelSeparation>${wheel_base}</wheelSeparation>
      <wheelDiameter>${wheel_radius*2}</wheelDiameter>
      <robotBaseFrame>base_link</robotBaseFrame>
      <torque>20</torque>
      <topicName>cmd_vel</topicName>
      <broadcastTF>true</broadcastTF>

      <num_wheel_pairs>2</num_wheel_pairs>

      <max_wheel_torque>20</max_wheel_torque>
      <max_wheel_acceleration>1.0</max_wheel_acceleration>


      <odometry_frame>odom</odometry_frame>
      <robot_base_frame>base_link</robot_base_frame>

      <publish_odom>true</publish_odom>
      <publish_odom_tf>true</publish_odom_tf>
      <publish_wheel_tf>true</publish_wheel_tf> -->

    </plugin>
  </gazebo>


</robot>
