<?xml version="1.0" ?>

<robot name="xacro_properties"
    xmlns:xacro="http://ros.org/wiki/xacro">

    <xacro:property name="wheel_thickness" value="0.025" />
    <xacro:property name="wheel_front_offset" value="-.13" />

    <xacro:macro name="wheel" params="lr fb name wheel_base wheel_radius">
        <joint name="wheel_${name}_joint" type="continuous">
            <parent link="base_link"/>
            <child link="wheel_${name}_link"/>
            <origin xyz="${wheel_front_offset/2 + (fb * (wheel_base / 2))} ${-lr * wheel_base/2} 0.0" rpy="0 0 ${lr*1.57}"/>
            <axis xyz="${-1*lr} 0 0"/>
        </joint>

        <link name="wheel_${name}_link">
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <mesh filename="package://deepdrive_description/meshes/wheels/rim.stl" scale="1 1 1"/>
                </geometry>
                <material name="blue"/>
            </visual>

            <collision>
                <origin xyz="0 0 0" rpy="${pi/2} 0 ${pi/2}"/>
                <geometry>
                    <cylinder length="${wheel_thickness}" radius="${wheel_radius}"/>
                </geometry>
            </collision>

            <inertial>
                <origin xyz="0 0 0" />
                <mass value="2.8498940e-02" />
                <inertia ixx="1.1175580e-05" ixy="-4.2369783e-11" ixz="-5.9381719e-09" iyy="1.1192413e-05" iyz="-1.4400107e-11" izz="2.0712558e-05" />
            </inertial>
        </link>

        <gazebo reference="wheel_${name}_link">
            <material>Gazebo/Blue</material>
        </gazebo>

        <joint name="tire_${name}_joint" type="fixed">
            <parent link="wheel_${name}_link"/>
            <child link="tire_${name}_link"/>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <axis xyz="1 1 1"/>
        </joint>

        <link name="tire_${name}_link">
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <mesh filename="package://deepdrive_description/meshes/wheels/tire.stl" scale="1 1 1"/>
                </geometry>
                <material name="black"/>
            </visual>

            <collision>
                <origin xyz="0 0 0" rpy="${pi/2} 0 ${pi/2}"/>
                <geometry>
                    <cylinder length="${wheel_thickness}" radius="${wheel_radius}"/>
                </geometry>
            </collision>

            <inertial>
                <origin xyz="0 0 0" />
                <mass value="2.8498940e-02" />
                <inertia ixx="1.1175580e-05" ixy="-4.2369783e-11" ixz="-5.9381719e-09" iyy="1.1192413e-05" iyz="-1.4400107e-11" izz="2.0712558e-05" />
            </inertial>
        </link>

        <gazebo reference="tire_${name}_link">
            <material>Gazebo/Black</material>
        </gazebo>
    </xacro:macro>

    
</robot>