imu_bno08x_publisher:
  ros__parameters:
    save_calibration: true
    publish_mag: true
    imu_frame: imu_base_link
    rate: 30
    address: 75
    frequency: 800000
    ned_to_enu: false
    i2c_bus: 1