deepdrive_node:
  ros__parameters:
    rate: 10
    wheels:
      separation: 0.287
      radius: 0.033
      ticks_per_rev: 320
    odometry:
      publish_tf: true
      publish_joints: true
      frame_id: "odom"
      child_frame_id: "base_footprint"
    # left_wheel_frames:
    #   - wheel_front_left_link
    #   - wheel_back_left_link
    # right_wheel_frames: 
    #   - wheel_front_right_link
    #   - wheel_back_right_link



